config/routes.rb
Freebase::Application.routes.draw do

  resources :freebases, only: [:index]
  resources :users, only: [:new, :create]

  root to: "freebases#index"

  get 'logout' => 'sessions#destroy', :as => "logout_sessions"  
  get 'login' => 'sessions#new', :as => "login_session"
  post 'login' => 'sessions#create', :as => "login_sessions"
  get 'results' => 'freebases#show', :as => "results_freebases"

end

app/models/freebase.rb
class Freebase < ActiveRecord::Base


# API_KEY = "AIzaSyBB35jT9xNiPClIOpf2Lo40kqI447b1Jz4"

	
# 	# def self.querying_freebase(params)
		
# 	# 	url = Addressable::URI.parse('https://www.googleapis.com/freebase/v1/search')
# 	# 	url.query_values = {
# 	# 	        'query' => params,
# 	# 	        'key'=> API_KEY
# 	# 	}
# 	# 	response = HTTParty.get(url, :format => :json)
# 	# 	response['result'].each { |topic|
# 	# 	  puts topic['name']
# 	# 	} 
# 	# end




end

app/models/user.rb
class User < ActiveRecord::Base
		has_secure_password
		before_create {generate_token(:auth_token)}

		attr_accessible :email, :password, :password_confirmation, :auth_token, :score
		validates_presence_of :email
		validates_uniqueness_of :email
		validates :email, format: {with: /.+@.{2,}\.[a-zA-Z]{2,6}/, message: "- must be a valid format"}
		validates_presence_of :password, :on => :create, :confirmation => true
		validates_confirmation_of :password

def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/freebases_controller.rb
class FreebasesController < ApplicationController

	 include ApplicationHelper

	 

	def index
		 current_user
				@results	= query_search(params[:query])
	end

	def show

		@resource

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include ApplicationHelper

	def new
	end


  def create
    user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
	    session[:auth_token] = user.auth_token
	    flash[:message] = "Welcome"
	    redirect_to :root
	  else
	  	flash[:error] = ["Invalid email or Password"]
	      redirect_to login_sessions_path
	  end
   end
 

  def destroy
    session.delete(:auth_token)
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper



	def new
		@user = User.new
	end


	def create
		user = User.create(params[:user])
		if user.id
			session[:auth_token] = user.auth_token
			flash[:message] = "Welcome!"
			redirect_to "/"
		else
			flash[:error] = user.errors.full_messages
			@user = User.new
			render :new
		end
	end

end

app/helpers/application_helper.rb
require 'rubygems'
require 'addressable/uri'

module ApplicationHelper

	def current_user
			@current_user ||= User.find_by_auth_token!(session[:auth_token]) if session[:auth_token]
	end



	API_KEY = "AIzaSyBB35jT9xNiPClIOpf2Lo40kqI447b1Jz4"

	def query_search(params)
			url = Addressable::URI.parse('https://www.googleapis.com/freebase/v1/search')
			url.query_values = {
			        'query' => params,
			        'key'=> API_KEY
			}
			response = HTTParty.get(url, :format => :json)
			response['result'].each { |topic|
			  puts topic['name']
			}
	end
end

app/views/freebases/index.html.erb
<% if flash[:message] %>
	<div class="container">
		<ul>
		 <li style ="color:red"><%= flash[:message] %> </li>
		</ul>
	</div>
<% end %>


<% if @current_user !=nil %>
 <%= "Welcome Back #{@current_user.email}" %>
<% end %>

<h1> Please enter your Search </h1>

<%= form_tag("/", method: 'get') do %>
	<%= label_tag("Search For") %>
	<%= text_field_tag :query, params[:query] %>
	<%= submit_tag("Search") %>
<% end %>


<div class "results">
<% if @results != nil %>

	<ul>
	<% @results.each do |result| %>
		<li><a href= "http://freebase.com<%= "#{result["mid"]}" %>"> <%= result["name"] %> </a> 
		<% if result["notable"] %>
		 Catagory<a href = "http://freebase.com<%= "#{result["notable"]["id"]}"%>"> <%= result["notable"]["name"] %></a> </li>
		<% else %>
		 </li>
		<% end %>
	<% end %>
	</ul>
<% end %>
</div>


<div class = "sign_up">
	<% if @current_user == nil %>
	 <%= link_to "Sign Up", new_user_path %>
	<% end %>
</div>

<div class = "sign_in">
	<% if @current_user == nil %>
	 <%= link_to "Sign In", login_session_path %>
	<% end %>
</div>

<div class = "log_out">
	<% if @current_user != nil %>
	 <%= link_to "log out", logout_sessions_path %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freebase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<% if flash[:error] %>
<div class="container">
<ul>
<% flash[:error].each do |error| %><br>
<li style="color:red"><%= error %> </li>
<% end %>
</ul>
</div>
<% end %>

<h1> Sign in to experience the awesomeness </h1>

<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.text_field :password %>
	<%= f.label :password_confirmation %>
	<%= f.text_field :password_confirmation %>
	<%= f.submit %>
<%end %>